## NumPy Basics 

NumPy's main object is the homogeneous multidimensional array. 

It is a table of elements (usually numbers), all of the same type, indexed by a tupleo f non-negative integers.

In [1]:
import numpy as np 

a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape

(3, 5)

In [3]:
a.ndim

2

In [4]:
a.dtype.name

'int64'

In [5]:
a.itemsize

8

In [6]:
a.size

15

Often the elements of an array are originally unknown, but its size is known. 

Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.

In [7]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [9]:
# To sequences of numbers, NumPy provides the arange function which is analogous to the Python built-in range, but returns an array.
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [10]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [11]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a - b
c

array([20, 29, 38, 47])

In [12]:
b ** 2

array([0, 1, 4, 9])

In [13]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [14]:
a < 35

array([ True,  True, False, False])

Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays.

The matrix product can be performed using the @ operator (in Python >= 3.5) or the dot function or method:

In [15]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

In [16]:
A * B

array([[2, 0],
       [0, 4]])

In [17]:
A @ B

array([[5, 4],
       [3, 4]])

### Universal Functions 

NumPy provides familiar mathematical functions such as sin, cos, and exp.

In NumPy, these are called "universal functions". Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [18]:
B = np.arange(3)
B

array([0, 1, 2])

In [19]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [20]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [22]:
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

### Indexing, Slicing and Iterating 

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [23]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [24]:
a[2]

8

In [25]:
a[2:5]

array([ 8, 27, 64])

In [26]:
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [27]:
a[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [28]:
for elem in a:
    print(elem ** (1 / 3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998
